# Week-7 Assignment 7.1

In [85]:
import pandas as pd
import numpy as np

# 1. Import the housing data as a data frame and ensure that the data is loaded properly.

In [86]:
# Read house price train data csv file 
house_price_data=pd.read_csv('house_price_train.csv')

In [87]:
house_price_data.dtypes

Id                 int64
MSSubClass         int64
MSZoning          object
LotFrontage      float64
LotArea            int64
                  ...
MoSold             int64
YrSold             int64
SaleType          object
SaleCondition     object
SalePrice          int64
Length: 81, dtype: object

In [88]:
house_price_data

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

# 2. Drop the "Id" column and any features that are missing more than 40% of their values.

In [89]:
house_price_data_df1= house_price_data.drop(['Id'],axis=1)

In [90]:
house_price_data_df1

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,Corner,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,FR2,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

In [91]:
missing_data_percent = (house_price_data_df1.isnull().sum()/len(house_price_data_df1)) * 100
df_columns_missing = pd.DataFrame({'column_name':house_price_data_df1.columns,
                                'missing_val_column':missing_data_percent})

In [92]:
df_columns_missing= df_columns_missing.loc[df_columns_missing['missing_val_column'] >= 40]

In [93]:
df_columns_missing

             column_name  missing_val_column
Alley              Alley           93.767123
FireplaceQu  FireplaceQu           47.260274
PoolQC            PoolQC           99.520548
Fence              Fence           80.753425
MiscFeature  MiscFeature           96.301370

In [94]:
df_columns_missing.dtypes

column_name            object
missing_val_column    float64
dtype: object

In [95]:
#delete columns with more than 40% missing data
house_price_data_df1.drop(['PoolQC','MiscFeature','Alley','Fence','FireplaceQu'], axis = 1,inplace=True)

In [96]:
house_price_data_df1.shape

(1460, 75)

# 3. For numerical columns, fill in any missing data with the median value.

In [97]:
# Get numeric columns 
df_house_price_num = house_price_data_df1.select_dtypes(exclude='object')

In [98]:
# Get Missing data numeric columns
numeric_missing_col = df_house_price_num.isnull().sum()
numeric_missing_col = numeric_missing_col[numeric_missing_col>0]
numeric_missing_col

LotFrontage    259
MasVnrArea       8
GarageYrBlt     81
dtype: int64

In [99]:
# Fill numeric missing data columns with median
house_price_data_df1[['LotFrontage','MasVnrArea','GarageYrBlt']] = house_price_data_df1[['LotFrontage','MasVnrArea','GarageYrBlt']].fillna('median')

In [100]:
house_price_data_df1

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,LandSlope,...,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,60,RL,65.0,8450,Pave,Reg,Lvl,AllPub,Inside,Gtl,...,0,0,0,0,0,2,2008,WD,Normal,208500
1,20,RL,80.0,9600,Pave,Reg,Lvl,AllPub,FR2,Gtl,...,0,0,0,0,0,5,2007,WD,Normal,181500
2,60,RL,68.0,11250,Pave,IR1,Lvl,AllPub,Inside,Gtl,...,0,0,0,0,0,9,2008,WD,Normal,223500
3,70,RL,60.0,9550,Pave,IR1,Lvl,AllPub,Corner,Gtl,...,272,0,0,0,0,2,2006,WD,Abnorml,140000
4,60,RL,84.0,14260,Pave,IR1,Lvl,AllPub,FR2,Gtl,...,0,0,0,0,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,60,RL,62.0,7917,Pave,Reg,Lvl,AllPub,Inside,Gtl,...,0,0,0,0,0,8,2007,WD,Normal,175000
1456,20,RL,85.0,13175,Pave,Reg,Lvl,AllPub,Inside,Gtl,...,0,0,0,0,0,2,2010,WD,Normal,210000
1457,70,RL,66.0,9042,Pave,Reg,Lvl,AllPub,Inside,Gtl,...,0,0,0,0,2500,5,2010,WD,Normal,266500
1458,20,RL,68.0,9717,Pave,Reg,Lvl,AllPub,Inside,Gtl,...,112,0,0,0,0,4,2010,WD,Normal,142125
1459,20,RL,75.0,9937,Pave,Reg,Lvl,AllPub,Inside,Gtl,...,0,0,0,0,0,6,2008,WD,Normal,147500

# 4. For categorical columns, fill in any missing data with the most common value (mode).

In [101]:
# Get categorical columns 
df_house_price_obj = house_price_data_df1.select_dtypes(include='object')

In [102]:
df_house_price_obj

,MSZoning,LotFrontage,Street,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,...,KitchenQual,Functional,GarageType,GarageYrBlt,GarageFinish,GarageQual,GarageCond,PavedDrive,SaleType,SaleCondition
0,RL,65.0,Pave,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,...,Gd,Typ,Attchd,2003.0,RFn,TA,TA,Y,WD,Normal
1,RL,80.0,Pave,Reg,Lvl,AllPub,FR2,Gtl,Veenker,Feedr,...,TA,Typ,Attchd,1976.0,RFn,TA,TA,Y,WD,Normal
2,RL,68.0,Pave,IR1,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,...,Gd,Typ,Attchd,2001.0,RFn,TA,TA,Y,WD,Normal
3,RL,60.0,Pave,IR1,Lvl,AllPub,Corner,Gtl,Crawfor,Norm,...,Gd,Typ,Detchd,1998.0,Unf,TA,TA,Y,WD,Abnorml
4,RL,84.0,Pave,IR1,Lvl,AllPub,FR2,Gtl,NoRidge,Norm,...,Gd,Typ,Attchd,2000.0,RFn,TA,TA,Y,WD,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,RL,62.0,Pave,Reg,Lvl,AllPub,Inside,Gtl,Gilbert,Norm,...,TA,Typ,Attchd,1999.0,RFn,TA,TA,Y,WD,Normal
1456,RL,85.0,Pave,Reg,Lvl,AllPub,Inside,Gtl,NWAmes,Norm,...,TA,Min1,Attchd,1978.0,Unf,TA,TA,Y,WD,Normal
1457,RL,66.0,Pave,Reg,Lvl,AllPub,Inside,Gtl,Crawfor,Norm,...,Gd,Typ,Attchd,1941.0,RFn,TA,TA,Y,WD,Normal
1458,RL,68.0,Pave,Reg,Lvl,AllPub,Inside,Gtl,NAmes,Norm,...,Gd,Typ,Attchd,1950.0,Unf,TA,TA,Y,WD,Normal
1459,RL,75.0,Pave,Reg,Lvl,AllPub,Inside,Gtl,Edwards,Norm,...,TA,Typ,Attchd,1965.0,Fin,TA,TA,Y,WD,Normal

In [103]:
obj_missing_col = df_house_price_obj.isnull().sum()
obj_missing_col = obj_missing_col[obj_missing_col>0]
obj_missing_col

MasVnrType       8
BsmtQual        37
BsmtCond        37
BsmtExposure    38
BsmtFinType1    37
BsmtFinType2    38
Electrical       1
GarageType      81
GarageFinish    81
GarageQual      81
GarageCond      81
dtype: int64

In [104]:
# Fill categorical missing data columns with mode value
house_price_data_df1[['MasVnrType', 'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1','BsmtFinType2', 'Electrical', 'GarageType', 'GarageFinish','GarageQual', 'GarageCond']] = house_price_data_df1[['MasVnrType', 'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1','BsmtFinType2', 'Electrical', 'GarageType', 'GarageFinish','GarageQual', 'GarageCond']].fillna(house_price_data.mode().iloc[0])

In [105]:
house_price_data_df1

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,LandSlope,...,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,60,RL,65.0,8450,Pave,Reg,Lvl,AllPub,Inside,Gtl,...,0,0,0,0,0,2,2008,WD,Normal,208500
1,20,RL,80.0,9600,Pave,Reg,Lvl,AllPub,FR2,Gtl,...,0,0,0,0,0,5,2007,WD,Normal,181500
2,60,RL,68.0,11250,Pave,IR1,Lvl,AllPub,Inside,Gtl,...,0,0,0,0,0,9,2008,WD,Normal,223500
3,70,RL,60.0,9550,Pave,IR1,Lvl,AllPub,Corner,Gtl,...,272,0,0,0,0,2,2006,WD,Abnorml,140000
4,60,RL,84.0,14260,Pave,IR1,Lvl,AllPub,FR2,Gtl,...,0,0,0,0,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,60,RL,62.0,7917,Pave,Reg,Lvl,AllPub,Inside,Gtl,...,0,0,0,0,0,8,2007,WD,Normal,175000
1456,20,RL,85.0,13175,Pave,Reg,Lvl,AllPub,Inside,Gtl,...,0,0,0,0,0,2,2010,WD,Normal,210000
1457,70,RL,66.0,9042,Pave,Reg,Lvl,AllPub,Inside,Gtl,...,0,0,0,0,2500,5,2010,WD,Normal,266500
1458,20,RL,68.0,9717,Pave,Reg,Lvl,AllPub,Inside,Gtl,...,112,0,0,0,0,4,2010,WD,Normal,142125
1459,20,RL,75.0,9937,Pave,Reg,Lvl,AllPub,Inside,Gtl,...,0,0,0,0,0,6,2008,WD,Normal,147500

In [106]:
# validate data for any null values.
house_price_data_df1.isnull().sum()

MSSubClass       0
MSZoning         0
LotFrontage      0
LotArea          0
Street           0
                ..
MoSold           0
YrSold           0
SaleType         0
SaleCondition    0
SalePrice        0
Length: 75, dtype: int64

# 5.Convert the categorical columns to dummy variables.

In [107]:
dum_house_data = pd.get_dummies(house_price_data_df1,drop_first=True)

In [108]:
dum_house_data.head()

,MSSubClass,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,BsmtFinSF1,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,...,SaleType_ConLI,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
0,60,8450,7,5,2003,2003,706,0,150,856,...,0,0,0,0,1,0,0,0,1,0
1,20,9600,6,8,1976,1976,978,0,284,1262,...,0,0,0,0,1,0,0,0,1,0
2,60,11250,7,5,2001,2002,486,0,434,920,...,0,0,0,0,1,0,0,0,1,0
3,70,9550,7,5,1915,1970,216,0,540,756,...,0,0,0,0,1,0,0,0,0,0
4,60,14260,8,5,2000,2000,655,0,490,1145,...,0,0,0,0,1,0,0,0,1,0

# 6.Split the data into a training and test set, where the SalePrice column is the target.

In [109]:
x = dum_house_data.drop('SalePrice',axis=1)
y = dum_house_data['SalePrice']

In [110]:
from sklearn.model_selection import train_test_split

In [111]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.20,random_state=101)

# 7.Run a linear regression and report the R2-value and RMSE on the test set.

In [112]:
# Linear regression import

from sklearn.linear_model import LinearRegression
Lr = LinearRegression()
Lr.fit(x_train,y_train)

LinearRegression()

In [113]:
y_pred = Lr.predict(x_test)

In [114]:
# Report RMSE and R Square
from sklearn.metrics import mean_squared_error,r2_score

In [115]:
MSE = mean_squared_error(y_test,y_pred).round(2)
RMSE = np.sqrt(MSE).round(2)
rsquare = Lr.score(x_train,y_train).round(2)

In [116]:
# MSE value
MSE

372600149752668.2

In [117]:
# RMSE Value
RMSE

19302853.41

In [118]:
# R Square
rsquare

0.98

# 8.Fit and transform the training features with a PCA so that 90% of the variance is retained

In [119]:
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

In [120]:
scale = StandardScaler()
x_train_scale = scale.fit_transform(x_train)

In [121]:
pca = PCA(n_components=0.99,whiten=True)

In [122]:
pca

PCA(n_components=0.99, whiten=True)

In [123]:
# Conduct PCA
features_pca = pca.fit_transform(x_train_scale)

In [124]:
features_pca.shape

(1168, 604)

# 9.How many features are in the PCA-transformed matrix?

In [125]:
print("Number of features in train data:",x_train_scale.shape[1])
print("Number of reduced features:",features_pca.shape[1])

Number of features in train data: 763
Number of reduced features: 604

# 10.Transform but DO NOT fit the test features with the same PCA.

In [126]:
x_test_scale = scale.transform(x_test)

# 11.Repeat step 7 with your PCA transformed data.

In [127]:
Lr.fit(x_train_scale,y_train)

LinearRegression()

In [128]:
y_pred1 = Lr.predict(x_test_scale)

In [129]:
MSE1 = mean_squared_error(y_test,y_pred1).round(2)
RMSE1 = np.sqrt(MSE1).round(2)
rsquare1 = Lr.score(x_train_scale,y_train).round(2)

In [130]:
MSE

372600149752668.2

In [131]:
RMSE

19302853.41

In [132]:
rsquare

0.98

# 12.Take your original training features (from step 6) and apply a min-max scaler to them.

In [133]:
# define min max scaler
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

In [134]:
# transform data
x_train_scaled = scaler.fit_transform(x_train)
print(x_train_scaled)

[[0.         0.05204113 0.55555556 ... 0.         1.         0.        ]
 [0.         0.04546815 0.66666667 ... 0.         0.         1.        ]
 [0.29411765 0.04988912 0.55555556 ... 0.         1.         0.        ]
 ...
 [0.82352941 0.00214733 0.55555556 ... 0.         1.         0.        ]
 [0.         0.06861626 0.66666667 ... 0.         1.         0.        ]
 [0.         0.03012809 0.44444444 ... 0.         1.         0.        ]]

# 13.Find the min-max scaled features in your training set that have a variance above 0.1(see Section 10.1 in the Machine Learning with Python Cookbook).

In [135]:
from sklearn.feature_selection import VarianceThreshold

In [136]:
thresholder = VarianceThreshold(threshold=0.1)

In [137]:
X_high_variance = thresholder.fit_transform(x_train_scaled)
#print(X_high_variance[0:7])

In [138]:
X_high_variance.shape

(1168, 44)

# 14.Transform but DO NOT fit the test features with the same steps applied in steps 11 and 12.14.

In [139]:
x_test_scaled = scaler.fit_transform(x_test)

In [140]:
# Run Linear Regression on created features.
Lr.fit(x_train_scaled,y_train)

LinearRegression()

In [141]:
y_pred2 = Lr.predict(x_test_scaled)

In [142]:
y_pred2

array([ 2.43871425e+15, -2.16553466e+15, -5.44118299e+15, -1.55740833e+14,
       -3.12888651e+15, -8.27981155e+15, -4.10368490e+15, -2.57944472e+15,
       -6.52229834e+15,  2.08265069e+14, -2.04594882e+15, -1.12171785e+16,
       -7.61047645e+14, -4.76952282e+15, -3.66691813e+15, -1.50912489e+15,
       -1.63356659e+16, -3.83416929e+15,  1.27588991e+15, -1.49316981e+16,
       -4.74914315e+15, -1.78075840e+15, -9.21760285e+15, -1.14107712e+15,
        2.41311456e+14, -9.18392631e+15,  9.73226800e+14, -1.28380316e+15,
       -2.91800181e+15, -4.60119250e+15,  2.07505650e+15, -8.35772431e+15,
       -3.72063860e+15, -3.17479716e+15, -7.22336861e+14, -1.82782004e+15,
       -1.89797594e+16,  1.85596569e+15, -3.43289039e+15, -1.95935061e+15,
        1.24272617e+15,  1.82630130e+15, -2.69243926e+14,  2.25909420e+15,
       -5.13200457e+15, -1.45394755e+15, -3.91992030e+15, -1.15105783e+16,
       -8.15343684e+15, -1.85272540e+15, -1.29516534e+16, -2.08721921e+15,
       -1.09035322e+16,  1.66163459e+15, -3.51414802e+15, -4.59853335e+14,
       -9.29732033e+15, -2.37855535e+15, -3.28814950e+15, -1.22431919e+16,
       -9.04152360e+15, -2.49450162e+15, -1.47605989e+15, -5.13803532e+15,
       -1.58349376e+15, -5.21558837e+15, -2.51849169e+15, -4.04307995e+15,
       -4.96776963e+15, -1.01339088e+16, -7.49907787e+15, -2.64386285e+15,
       -4.31398670e+15, -8.77268794e+13, -3.63917326e+15, -8.93135066e+14,
        1.27088590e+14,  4.72815761e+15, -3.32986769e+15, -6.29579272e+14,
       -5.03713556e+15, -2.14286928e+15, -2.78947113e+15, -3.71193660e+15,
        1.91946689e+14, -1.43642139e+15, -7.51479464e+15, -5.00344486e+15,
       -1.06307559e+14,  3.03665088e+15, -1.52863307e+15, -1.23021877e+16,
       -5.72191017e+15, -4.16265399e+15, -3.36929401e+15, -1.27777011e+16,
       -3.95444713e+15, -4.67719683e+15, -1.12893453e+16,  2.47754185e+15,
       -5.08444137e+15, -1.04211779e+16, -7.83140888e+15, -3.71131075e+15,
       -6.01233137e+15, -5.77522292e+15, -2.17282846e+15,  2.27944845e+15,
        2.19850898e+15, -7.67256125e+14,  1.54951055e+15,  3.18969567e+14,
       -1.75320976e+15,  8.10142912e+14, -1.02788214e+16, -1.12616232e+16,
       -5.15804014e+15,  2.82107362e+15, -1.35313038e+16, -1.55431265e+15,
       -6.61643924e+14, -1.29718758e+16,  1.09697022e+14, -3.57629599e+15,
       -8.03592705e+14,  9.90980458e+14, -8.50530999e+15, -9.81188084e+15,
       -1.82782004e+15, -3.08100909e+15, -1.28502784e+16, -6.03782644e+15,
       -1.24824106e+15,  2.65799659e+15, -5.93033864e+14,  1.80839028e+15,
       -4.27821778e+15, -3.14684269e+15, -1.98509657e+16, -9.95679342e+15,
       -3.85907712e+15,  2.07915314e+15, -5.01334806e+15, -5.04767155e+15,
       -6.83438262e+14, -3.81511713e+15, -3.46375501e+15, -8.85888779e+14,
        2.18327230e+15, -1.31501008e+14, -8.41600894e+15,  3.60516754e+15,
       -1.13786666e+16, -3.61627174e+15, -1.39705175e+16, -1.62799989e+15,
       -5.01732135e+15,  5.37811228e+14, -7.61318264e+15, -2.53436049e+15,
       -4.53880564e+15, -4.34138593e+13, -5.69867900e+15,  6.27381438e+15,
       -3.69595443e+15, -8.84207354e+15, -3.92745968e+15, -1.23356786e+15,
       -1.12536339e+16, -3.55723189e+15, -2.94809025e+15, -3.65228085e+14,
       -3.33750238e+15,  2.90224754e+15, -3.94801264e+15, -1.78529184e+14,
       -1.15475554e+16, -3.01562371e+15, -1.65624236e+15, -1.33219856e+16,
       -1.10597392e+16, -3.63791498e+15, -4.34897594e+15, -6.73386766e+15,
       -3.90409992e+15, -3.17989048e+15, -2.52587227e+15, -3.08932204e+15,
       -3.94542235e+15, -4.46864338e+15, -3.02596269e+15, -5.64067309e+15,
       -7.99242286e+15, -2.61294938e+15, -2.04862857e+15, -3.78072119e+15,
       -3.06531608e+15, -5.32915416e+15, -1.01410804e+16, -6.21295675e+15,
       -5.42653705e+15, -7.03157500e+15, -3.99198084e+15, -1.41890556e+15,
       -1.66710764e+16, -1.82782004e+15, -3.52928701e+15, -2.02093253e+15,
       -1.30151796e+15, -2.95720687e+15, -1.35867107e+15, -5.78314266e+15,
       -2.02319626e+15, -5.37330307e+15, -2.14557137e+15, -2.32801803e+15,
       -1.28599794e+16, -2.05426308e+15, -3.43936704e+14,  2.21447943e+15,
       -7.37589840e+15, -6.60770264e+15, -6.58643883e+15, -3.37162140e+15,
       -4.30326604e+15, -1.08609189e+15, -1.41473284e+15, -3.25849555e+15,
       -3.36234342e+15, -1.44683787e+16, -8.76536621e+15, -1.21915590e+15,
       -2.97314434e+15, -1.30013749e+15, -5.64508993e+15, -6.08545765e+14,
       -5.00044933e+15, -4.17599773e+15, -5.64329014e+15, -1.05526066e+16,
       -2.28914044e+15, -1.16474402e+16,  1.78125284e+14, -9.36980793e+14,
        2.73493410e+15, -1.00856046e+16, -2.23016599e+15, -3.05826075e+15,
       -5.18473304e+14, -7.16259533e+14, -2.86614898e+15, -3.48927446e+15,
       -5.69344436e+15, -2.57043383e+15, -6.04904979e+15, -1.38918683e+15,
       -2.95423190e+15, -1.27094469e+15, -7.92471985e+15, -1.46906044e+16,
       -2.68330594e+15, -7.38997136e+14, -7.91287216e+14, -1.01749174e+16,
       -1.20941750e+15, -4.28145044e+15, -5.60986137e+15, -1.24234111e+16,
       -7.67509512e+15, -1.15759685e+16, -6.51109425e+15, -4.69496954e+15,
       -5.43248502e+15, -2.46662522e+15, -1.40535871e+16, -5.25744235e+15,
       -3.37162140e+15, -3.66969815e+15,  1.28722720e+15, -9.29602771e+14,
       -1.99861023e+15, -5.06884136e+15, -5.59191658e+14, -9.18036982e+14,
       -9.08465995e+15, -3.56305445e+15, -1.11416058e+15, -1.45050811e+15,
       -9.69453734e+14, -4.33780771e+15, -3.20592781e+15, -1.47090648e+15])

# 15.Repeat step 7 with the high variance data.

In [143]:
MSE2 = mean_squared_error(y_test,y_pred2).round(2)
RMSE2 = np.sqrt(MSE2).round(2)
rsquare2 = Lr.score(x_train_scaled,y_train).round(2)

In [144]:
MSE

372600149752668.2

In [145]:
RMSE2

5943759528853047.0

In [146]:
rsquare2

0.98

# 16.Summarize your findings.

The above output concludes that even after using the PCA to reduce the numbe rof features the the rsqare is same across with all feature and reduced fature, the out uts tell us that before applying the PCA we should train the model first.